apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-agent
          mountPath: /etc/nginx-agent
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: module-includes
          mountPath: /etc/nginx/module-includes
        - name: nginx-secrets
          mountPath: /etc/nginx/secrets
        - name: nginx-run
          mountPath: /var/run/nginx
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-includes
          mountPath: /etc/nginx/includes
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      volumes:
      - name: nginx-agent
        configMap:
          name: nginx-agent-config
      - name: nginx-conf
        emptyDir: {}
      - name: module-includes
        emptyDir: {}
      - name: nginx-secrets
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-includes
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-agent-config
data:
  nginx-agent.conf: |-
    command:
      server:
        host: ngf-nginx-gateway-fabric.nginx-gateway.svc
        port: 8443
        type: grpc
    log:
      level: debug
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
