//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/nginx/nginx-gateway-fabric/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
	apisv1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxLogging) DeepCopyInto(out *NginxLogging) {
	*out = *in
	if in.ErrorLevel != nil {
		in, out := &in.ErrorLevel, &out.ErrorLevel
		*out = new(NginxErrorLogLevel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxLogging.
func (in *NginxLogging) DeepCopy() *NginxLogging {
	if in == nil {
		return nil
	}
	out := new(NginxLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxPlus) DeepCopyInto(out *NginxPlus) {
	*out = *in
	if in.AllowedAddresses != nil {
		in, out := &in.AllowedAddresses, &out.AllowedAddresses
		*out = make([]NginxPlusAllowAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxPlus.
func (in *NginxPlus) DeepCopy() *NginxPlus {
	if in == nil {
		return nil
	}
	out := new(NginxPlus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxPlusAllowAddress) DeepCopyInto(out *NginxPlusAllowAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxPlusAllowAddress.
func (in *NginxPlusAllowAddress) DeepCopy() *NginxPlusAllowAddress {
	if in == nil {
		return nil
	}
	out := new(NginxPlusAllowAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxProxy) DeepCopyInto(out *NginxProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxProxy.
func (in *NginxProxy) DeepCopy() *NginxProxy {
	if in == nil {
		return nil
	}
	out := new(NginxProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NginxProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxProxyList) DeepCopyInto(out *NginxProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NginxProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxProxyList.
func (in *NginxProxyList) DeepCopy() *NginxProxyList {
	if in == nil {
		return nil
	}
	out := new(NginxProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NginxProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxProxySpec) DeepCopyInto(out *NginxProxySpec) {
	*out = *in
	if in.IPFamily != nil {
		in, out := &in.IPFamily, &out.IPFamily
		*out = new(IPFamilyType)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(Telemetry)
		(*in).DeepCopyInto(*out)
	}
	if in.RewriteClientIP != nil {
		in, out := &in.RewriteClientIP, &out.RewriteClientIP
		*out = new(RewriteClientIP)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(NginxLogging)
		(*in).DeepCopyInto(*out)
	}
	if in.NginxPlus != nil {
		in, out := &in.NginxPlus, &out.NginxPlus
		*out = new(NginxPlus)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableHTTP2 != nil {
		in, out := &in.DisableHTTP2, &out.DisableHTTP2
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxProxySpec.
func (in *NginxProxySpec) DeepCopy() *NginxProxySpec {
	if in == nil {
		return nil
	}
	out := new(NginxProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityPolicy) DeepCopyInto(out *ObservabilityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityPolicy.
func (in *ObservabilityPolicy) DeepCopy() *ObservabilityPolicy {
	if in == nil {
		return nil
	}
	out := new(ObservabilityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObservabilityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityPolicyList) DeepCopyInto(out *ObservabilityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObservabilityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityPolicyList.
func (in *ObservabilityPolicyList) DeepCopy() *ObservabilityPolicyList {
	if in == nil {
		return nil
	}
	out := new(ObservabilityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObservabilityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityPolicySpec) DeepCopyInto(out *ObservabilityPolicySpec) {
	*out = *in
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(Tracing)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]apisv1alpha2.LocalPolicyTargetReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityPolicySpec.
func (in *ObservabilityPolicySpec) DeepCopy() *ObservabilityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RewriteClientIP) DeepCopyInto(out *RewriteClientIP) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(RewriteClientIPModeType)
		**out = **in
	}
	if in.SetIPRecursively != nil {
		in, out := &in.SetIPRecursively, &out.SetIPRecursively
		*out = new(bool)
		**out = **in
	}
	if in.TrustedAddresses != nil {
		in, out := &in.TrustedAddresses, &out.TrustedAddresses
		*out = make([]RewriteClientIPAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RewriteClientIP.
func (in *RewriteClientIP) DeepCopy() *RewriteClientIP {
	if in == nil {
		return nil
	}
	out := new(RewriteClientIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RewriteClientIPAddress) DeepCopyInto(out *RewriteClientIPAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RewriteClientIPAddress.
func (in *RewriteClientIPAddress) DeepCopy() *RewriteClientIPAddress {
	if in == nil {
		return nil
	}
	out := new(RewriteClientIPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Telemetry) DeepCopyInto(out *Telemetry) {
	*out = *in
	if in.DisabledFeatures != nil {
		in, out := &in.DisabledFeatures, &out.DisabledFeatures
		*out = make([]DisableTelemetryFeature, len(*in))
		copy(*out, *in)
	}
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(TelemetryExporter)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.SpanAttributes != nil {
		in, out := &in.SpanAttributes, &out.SpanAttributes
		*out = make([]v1alpha1.SpanAttribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry.
func (in *Telemetry) DeepCopy() *Telemetry {
	if in == nil {
		return nil
	}
	out := new(Telemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryExporter) DeepCopyInto(out *TelemetryExporter) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1alpha1.Duration)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.BatchCount != nil {
		in, out := &in.BatchCount, &out.BatchCount
		*out = new(int32)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryExporter.
func (in *TelemetryExporter) DeepCopy() *TelemetryExporter {
	if in == nil {
		return nil
	}
	out := new(TelemetryExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
	if in.Ratio != nil {
		in, out := &in.Ratio, &out.Ratio
		*out = new(int32)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(TraceContext)
		**out = **in
	}
	if in.SpanName != nil {
		in, out := &in.SpanName, &out.SpanName
		*out = new(string)
		**out = **in
	}
	if in.SpanAttributes != nil {
		in, out := &in.SpanAttributes, &out.SpanAttributes
		*out = make([]v1alpha1.SpanAttribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}
