// Code generated by counterfeiter. DO NOT EDIT.
package agentfakes

import (
	"context"
	"sync"

	"github.com/nginxinc/nginx-gateway-fabric/internal/mode/static/nginx/agent"
	"github.com/nginxinc/nginx-gateway-fabric/internal/mode/static/state/dataplane"
	"k8s.io/apimachinery/pkg/types"
)

type FakeNginxUpdater struct {
	UpdateConfigStub        func(context.Context, types.NamespacedName, []agent.File) error
	updateConfigMutex       sync.RWMutex
	updateConfigArgsForCall []struct {
		arg1 context.Context
		arg2 types.NamespacedName
		arg3 []agent.File
	}
	updateConfigReturns struct {
		result1 error
	}
	updateConfigReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateUpstreamServersStub        func(context.Context, types.NamespacedName, dataplane.Configuration) error
	updateUpstreamServersMutex       sync.RWMutex
	updateUpstreamServersArgsForCall []struct {
		arg1 context.Context
		arg2 types.NamespacedName
		arg3 dataplane.Configuration
	}
	updateUpstreamServersReturns struct {
		result1 error
	}
	updateUpstreamServersReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNginxUpdater) UpdateConfig(arg1 context.Context, arg2 types.NamespacedName, arg3 []agent.File) error {
	var arg3Copy []agent.File
	if arg3 != nil {
		arg3Copy = make([]agent.File, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.updateConfigMutex.Lock()
	ret, specificReturn := fake.updateConfigReturnsOnCall[len(fake.updateConfigArgsForCall)]
	fake.updateConfigArgsForCall = append(fake.updateConfigArgsForCall, struct {
		arg1 context.Context
		arg2 types.NamespacedName
		arg3 []agent.File
	}{arg1, arg2, arg3Copy})
	stub := fake.UpdateConfigStub
	fakeReturns := fake.updateConfigReturns
	fake.recordInvocation("UpdateConfig", []interface{}{arg1, arg2, arg3Copy})
	fake.updateConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNginxUpdater) UpdateConfigCallCount() int {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	return len(fake.updateConfigArgsForCall)
}

func (fake *FakeNginxUpdater) UpdateConfigCalls(stub func(context.Context, types.NamespacedName, []agent.File) error) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = stub
}

func (fake *FakeNginxUpdater) UpdateConfigArgsForCall(i int) (context.Context, types.NamespacedName, []agent.File) {
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	argsForCall := fake.updateConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeNginxUpdater) UpdateConfigReturns(result1 error) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = nil
	fake.updateConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNginxUpdater) UpdateConfigReturnsOnCall(i int, result1 error) {
	fake.updateConfigMutex.Lock()
	defer fake.updateConfigMutex.Unlock()
	fake.UpdateConfigStub = nil
	if fake.updateConfigReturnsOnCall == nil {
		fake.updateConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNginxUpdater) UpdateUpstreamServers(arg1 context.Context, arg2 types.NamespacedName, arg3 dataplane.Configuration) error {
	fake.updateUpstreamServersMutex.Lock()
	ret, specificReturn := fake.updateUpstreamServersReturnsOnCall[len(fake.updateUpstreamServersArgsForCall)]
	fake.updateUpstreamServersArgsForCall = append(fake.updateUpstreamServersArgsForCall, struct {
		arg1 context.Context
		arg2 types.NamespacedName
		arg3 dataplane.Configuration
	}{arg1, arg2, arg3})
	stub := fake.UpdateUpstreamServersStub
	fakeReturns := fake.updateUpstreamServersReturns
	fake.recordInvocation("UpdateUpstreamServers", []interface{}{arg1, arg2, arg3})
	fake.updateUpstreamServersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersCallCount() int {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	return len(fake.updateUpstreamServersArgsForCall)
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersCalls(stub func(context.Context, types.NamespacedName, dataplane.Configuration) error) {
	fake.updateUpstreamServersMutex.Lock()
	defer fake.updateUpstreamServersMutex.Unlock()
	fake.UpdateUpstreamServersStub = stub
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersArgsForCall(i int) (context.Context, types.NamespacedName, dataplane.Configuration) {
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	argsForCall := fake.updateUpstreamServersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersReturns(result1 error) {
	fake.updateUpstreamServersMutex.Lock()
	defer fake.updateUpstreamServersMutex.Unlock()
	fake.UpdateUpstreamServersStub = nil
	fake.updateUpstreamServersReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNginxUpdater) UpdateUpstreamServersReturnsOnCall(i int, result1 error) {
	fake.updateUpstreamServersMutex.Lock()
	defer fake.updateUpstreamServersMutex.Unlock()
	fake.UpdateUpstreamServersStub = nil
	if fake.updateUpstreamServersReturnsOnCall == nil {
		fake.updateUpstreamServersReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateUpstreamServersReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNginxUpdater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.updateConfigMutex.RLock()
	defer fake.updateConfigMutex.RUnlock()
	fake.updateUpstreamServersMutex.RLock()
	defer fake.updateUpstreamServersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNginxUpdater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agent.NginxUpdater = new(FakeNginxUpdater)
